/*!
 * node-minify
 * Copyright (c) 2011-2026 Rodolphe Stoclin
 * MIT Licensed
 */

import { info, warning } from "@actions/core";
import { context, getOctokit } from "@actions/github";
import { prettyBytes } from "@node-minify/utils";
import type { MinifyResult } from "../types.ts";

const COMMENT_TAG = "<!-- node-minify-report -->";

/**
 * Posts or updates a pull request comment with a minification report.
 *
 * @param result - Minification results containing per-file metrics, totals, compressor name, and execution time
 * @param githubToken - GitHub API token used to authenticate requests; when `undefined`, the function skips posting
 */
export async function postPRComment(
    result: MinifyResult,
    githubToken: string | undefined
): Promise<void> {
    if (!githubToken) {
        warning("No GitHub token provided, skipping PR comment");
        return;
    }

    const prNumber = context.payload.pull_request?.number;
    if (!prNumber) {
        warning("Not a pull request, skipping PR comment");
        return;
    }

    const octokit = getOctokit(githubToken);
    const { owner, repo } = context.repo;

    const body = generateCommentBody(result);

    const comments = await octokit.paginate(octokit.rest.issues.listComments, {
        owner,
        repo,
        issue_number: prNumber,
    });

    const existingComment = comments.find((c) => c.body?.includes(COMMENT_TAG));

    if (existingComment) {
        await octokit.rest.issues.updateComment({
            owner,
            repo,
            comment_id: existingComment.id,
            body,
        });
        info(`Updated existing PR comment #${existingComment.id}`);
    } else {
        const { data: newComment } = await octokit.rest.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body,
        });
        info(`Created new PR comment #${newComment.id}`);
    }
}

/**
 * Builds the Markdown body for the node-minify PR comment, including a per-file table, totals, and a configuration section.
 *
 * @param result - Minification results used to populate the report (expects `files`, `totalOriginalSize`, `totalMinifiedSize`, `totalReduction`, `compressor`, and `totalTimeMs`)
 * @returns The Markdown string for the PR comment, beginning with `COMMENT_TAG` and containing the file table, total summary, and configuration details
 */
function generateCommentBody(result: MinifyResult): string {
    const filesTable = result.files
        .map(
            (f) =>
                `| \`${f.file}\` | ${prettyBytes(f.originalSize)} | ${prettyBytes(f.minifiedSize)} | ${f.reduction.toFixed(1)}% |`
        )
        .join("\n");

    return `${COMMENT_TAG}
## 📦 node-minify Report

| File | Original | Minified | Reduction |
|------|----------|----------|-----------|
${filesTable}

**Total:** ${prettyBytes(result.totalOriginalSize)} → ${prettyBytes(result.totalMinifiedSize)} (${result.totalReduction.toFixed(1)}% reduction)

<details>
<summary>Configuration</summary>

- **Compressor:** ${result.compressor}
- **Time:** ${result.totalTimeMs}ms

</details>

---
*Generated by [node-minify](https://github.com/srod/node-minify) action*
`;
}
